- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
    enabled: true
- name: Restart prometheus
  ansible.builtin.service:
    name: prometheus
    daemon_reload: true
    state: restarted
    enabled: true
- name: Restart grafana
  ansible.builtin.service:
    name: grafana-server
    state: restarted
    enabled: true
